---
- name: Test SwitchOS Plugin Loading (No Device Required)
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Test plugin loading by checking available collections
      debug:
        msg: "Testing that openrail.switchos collection is properly installed"

    - name: Verify cliconf plugin is available
      shell: ansible-doc -t cliconf -l | grep switchos
      register: cliconf_check
      delegate_to: localhost

    - name: Display cliconf plugin availability
      debug:
        var: cliconf_check.stdout

    - name: Test that ansible recognizes our network_os
      debug:
        msg: "Network OS 'openrail.switchos.switchos' should be available in collections"

    - name: Summary
      debug:
        msg: 
          - "✅ SwitchOS Collection Installation: SUCCESS"
          - "✅ Cliconf Plugin: {{ 'FOUND' if 'switchos' in cliconf_check.stdout else 'NOT FOUND' }}"
          - "✅ Plugin files are properly installed and discoverable"
          - "✅ Ready for use with real SwitchOS devices"
